### PR TITLE
Using tcp to connect libvirt from devops

### PR DESCRIPTION
**Pull request by teran**
BEWARE: It's necessary to enable tcp socket listening in libvirt
 Tested with several environment configurations, works much faster and cleaner.

### CODE REVIEW

**Comment by teran** [comment]
Maybe merge ?:)

**Comment by xdel** [comment]
+1

**Comment by xarses** [comment]
-1, Please document how to "enable tcp socket listening in libvirt"

**Comment by teran** [comment]
Will open new one when create doc and from separate branch.

**Pull request closed without merging**
