### PR TITLE
Add support to change inteface model from virtio

### PR DESCRIPTION
**Pull request by xarses**
Add e1000, pcnet, rtl8139 to choices for model and test to ensure it updates.

This is needed to help with testing alternate drivers that sometimes need to
 be tested for errors.

Closes-bug #1257513
https://bugs.launchpad.net/fuel/+bug/1257513

### CODE REVIEW

**Comment by xarses** [comment]
verified by manual testing

**Comment by xarses** [comment]
I didn't need it. Ideally the valid choices should come from the hypervisor driver or just not be validated, but this seems to be the best option at this time.

**Comment by teran** [comment]
I tried to google a little to found if libvirt python module can provide the list of drivers, but it looks like no. Don't you wanna add net2k_pci to that list for maximum compability?

**Comment by teran** [comment]
verified, works fine. +1.

**Pull request merged**
